# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/godka/jlc/openlitespeed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/godka/jlc/openlitespeed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/godka/jlc/openlitespeed/CMakeFiles /home/godka/jlc/openlitespeed/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/godka/jlc/openlitespeed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ls_shmhashstat

# Build rule for target.
ls_shmhashstat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ls_shmhashstat
.PHONY : ls_shmhashstat

# fast build rule for target.
ls_shmhashstat/fast:
	$(MAKE) -f src/CMakeFiles/ls_shmhashstat.dir/build.make src/CMakeFiles/ls_shmhashstat.dir/build
.PHONY : ls_shmhashstat/fast

#=============================================================================
# Target rules for targets named ls_shmstat

# Build rule for target.
ls_shmstat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ls_shmstat
.PHONY : ls_shmstat

# fast build rule for target.
ls_shmstat/fast:
	$(MAKE) -f src/CMakeFiles/ls_shmstat.dir/build.make src/CMakeFiles/ls_shmstat.dir/build
.PHONY : ls_shmstat/fast

#=============================================================================
# Target rules for targets named openlitespeed

# Build rule for target.
openlitespeed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openlitespeed
.PHONY : openlitespeed

# fast build rule for target.
openlitespeed/fast:
	$(MAKE) -f src/CMakeFiles/openlitespeed.dir/build.make src/CMakeFiles/openlitespeed.dir/build
.PHONY : openlitespeed/fast

#=============================================================================
# Target rules for targets named adns

# Build rule for target.
adns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adns
.PHONY : adns

# fast build rule for target.
adns/fast:
	$(MAKE) -f src/adns/CMakeFiles/adns.dir/build.make src/adns/CMakeFiles/adns.dir/build
.PHONY : adns/fast

#=============================================================================
# Target rules for targets named edio

# Build rule for target.
edio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edio
.PHONY : edio

# fast build rule for target.
edio/fast:
	$(MAKE) -f src/edio/CMakeFiles/edio.dir/build.make src/edio/CMakeFiles/edio.dir/build
.PHONY : edio/fast

#=============================================================================
# Target rules for targets named extensions

# Build rule for target.
extensions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extensions
.PHONY : extensions

# fast build rule for target.
extensions/fast:
	$(MAKE) -f src/extensions/CMakeFiles/extensions.dir/build.make src/extensions/CMakeFiles/extensions.dir/build
.PHONY : extensions/fast

#=============================================================================
# Target rules for targets named fcgi

# Build rule for target.
fcgi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcgi
.PHONY : fcgi

# fast build rule for target.
fcgi/fast:
	$(MAKE) -f src/extensions/fcgi/CMakeFiles/fcgi.dir/build.make src/extensions/fcgi/CMakeFiles/fcgi.dir/build
.PHONY : fcgi/fast

#=============================================================================
# Target rules for targets named cgi

# Build rule for target.
cgi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgi
.PHONY : cgi

# fast build rule for target.
cgi/fast:
	$(MAKE) -f src/extensions/cgi/CMakeFiles/cgi.dir/build.make src/extensions/cgi/CMakeFiles/cgi.dir/build
.PHONY : cgi/fast

#=============================================================================
# Target rules for targets named jk

# Build rule for target.
jk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jk
.PHONY : jk

# fast build rule for target.
jk/fast:
	$(MAKE) -f src/extensions/jk/CMakeFiles/jk.dir/build.make src/extensions/jk/CMakeFiles/jk.dir/build
.PHONY : jk/fast

#=============================================================================
# Target rules for targets named proxy

# Build rule for target.
proxy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 proxy
.PHONY : proxy

# fast build rule for target.
proxy/fast:
	$(MAKE) -f src/extensions/proxy/CMakeFiles/proxy.dir/build.make src/extensions/proxy/CMakeFiles/proxy.dir/build
.PHONY : proxy/fast

#=============================================================================
# Target rules for targets named registry

# Build rule for target.
registry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 registry
.PHONY : registry

# fast build rule for target.
registry/fast:
	$(MAKE) -f src/extensions/registry/CMakeFiles/registry.dir/build.make src/extensions/registry/CMakeFiles/registry.dir/build
.PHONY : registry/fast

#=============================================================================
# Target rules for targets named lsapi

# Build rule for target.
lsapi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsapi
.PHONY : lsapi

# fast build rule for target.
lsapi/fast:
	$(MAKE) -f src/extensions/lsapi/CMakeFiles/lsapi.dir/build.make src/extensions/lsapi/CMakeFiles/lsapi.dir/build
.PHONY : lsapi/fast

#=============================================================================
# Target rules for targets named http

# Build rule for target.
http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http
.PHONY : http

# fast build rule for target.
http/fast:
	$(MAKE) -f src/http/CMakeFiles/http.dir/build.make src/http/CMakeFiles/http.dir/build
.PHONY : http/fast

#=============================================================================
# Target rules for targets named lsquic

# Build rule for target.
lsquic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsquic
.PHONY : lsquic

# fast build rule for target.
lsquic/fast:
	$(MAKE) -f src/liblsquic/CMakeFiles/lsquic.dir/build.make src/liblsquic/CMakeFiles/lsquic.dir/build
.PHONY : lsquic/fast

#=============================================================================
# Target rules for targets named log4cxx

# Build rule for target.
log4cxx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log4cxx
.PHONY : log4cxx

# fast build rule for target.
log4cxx/fast:
	$(MAKE) -f src/log4cxx/CMakeFiles/log4cxx.dir/build.make src/log4cxx/CMakeFiles/log4cxx.dir/build
.PHONY : log4cxx/fast

#=============================================================================
# Target rules for targets named lsiapi

# Build rule for target.
lsiapi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsiapi
.PHONY : lsiapi

# fast build rule for target.
lsiapi/fast:
	$(MAKE) -f src/lsiapi/CMakeFiles/lsiapi.dir/build.make src/lsiapi/CMakeFiles/lsiapi.dir/build
.PHONY : lsiapi/fast

#=============================================================================
# Target rules for targets named lsr

# Build rule for target.
lsr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsr
.PHONY : lsr

# fast build rule for target.
lsr/fast:
	$(MAKE) -f src/lsr/CMakeFiles/lsr.dir/build.make src/lsr/CMakeFiles/lsr.dir/build
.PHONY : lsr/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f src/main/CMakeFiles/main.dir/build.make src/main/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named modgzip

# Build rule for target.
modgzip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modgzip
.PHONY : modgzip

# fast build rule for target.
modgzip/fast:
	$(MAKE) -f src/modules/modgzip/CMakeFiles/modgzip.dir/build.make src/modules/modgzip/CMakeFiles/modgzip.dir/build
.PHONY : modgzip/fast

#=============================================================================
# Target rules for targets named cache

# Build rule for target.
cache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cache
.PHONY : cache

# fast build rule for target.
cache/fast:
	$(MAKE) -f src/modules/cache/CMakeFiles/cache.dir/build.make src/modules/cache/CMakeFiles/cache.dir/build
.PHONY : cache/fast

#=============================================================================
# Target rules for targets named modreqparser

# Build rule for target.
modreqparser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modreqparser
.PHONY : modreqparser

# fast build rule for target.
modreqparser/fast:
	$(MAKE) -f src/modules/modreqparser/CMakeFiles/modreqparser.dir/build.make src/modules/modreqparser/CMakeFiles/modreqparser.dir/build
.PHONY : modreqparser/fast

#=============================================================================
# Target rules for targets named modinspector

# Build rule for target.
modinspector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modinspector
.PHONY : modinspector

# fast build rule for target.
modinspector/fast:
	$(MAKE) -f src/modules/modinspector/CMakeFiles/modinspector.dir/build.make src/modules/modinspector/CMakeFiles/modinspector.dir/build
.PHONY : modinspector/fast

#=============================================================================
# Target rules for targets named uploadprogress

# Build rule for target.
uploadprogress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uploadprogress
.PHONY : uploadprogress

# fast build rule for target.
uploadprogress/fast:
	$(MAKE) -f src/modules/uploadprogress/CMakeFiles/uploadprogress.dir/build.make src/modules/uploadprogress/CMakeFiles/uploadprogress.dir/build
.PHONY : uploadprogress/fast

#=============================================================================
# Target rules for targets named mod_security

# Build rule for target.
mod_security: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_security
.PHONY : mod_security

# fast build rule for target.
mod_security/fast:
	$(MAKE) -f src/modules/modsecurity-ls/CMakeFiles/mod_security.dir/build.make src/modules/modsecurity-ls/CMakeFiles/mod_security.dir/build
.PHONY : mod_security/fast

#=============================================================================
# Target rules for targets named modpagespeed

# Build rule for target.
modpagespeed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modpagespeed
.PHONY : modpagespeed

# fast build rule for target.
modpagespeed/fast:
	$(MAKE) -f src/modules/pagespeed/CMakeFiles/modpagespeed.dir/build.make src/modules/pagespeed/CMakeFiles/modpagespeed.dir/build
.PHONY : modpagespeed/fast

#=============================================================================
# Target rules for targets named quic

# Build rule for target.
quic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quic
.PHONY : quic

# fast build rule for target.
quic/fast:
	$(MAKE) -f src/quic/CMakeFiles/quic.dir/build.make src/quic/CMakeFiles/quic.dir/build
.PHONY : quic/fast

#=============================================================================
# Target rules for targets named lsshm

# Build rule for target.
lsshm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsshm
.PHONY : lsshm

# fast build rule for target.
lsshm/fast:
	$(MAKE) -f src/shm/CMakeFiles/lsshm.dir/build.make src/shm/CMakeFiles/lsshm.dir/build
.PHONY : lsshm/fast

#=============================================================================
# Target rules for targets named socket

# Build rule for target.
socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 socket
.PHONY : socket

# fast build rule for target.
socket/fast:
	$(MAKE) -f src/socket/CMakeFiles/socket.dir/build.make src/socket/CMakeFiles/socket.dir/build
.PHONY : socket/fast

#=============================================================================
# Target rules for targets named spdy

# Build rule for target.
spdy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spdy
.PHONY : spdy

# fast build rule for target.
spdy/fast:
	$(MAKE) -f src/spdy/CMakeFiles/spdy.dir/build.make src/spdy/CMakeFiles/spdy.dir/build
.PHONY : spdy/fast

#=============================================================================
# Target rules for targets named sslpp

# Build rule for target.
sslpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sslpp
.PHONY : sslpp

# fast build rule for target.
sslpp/fast:
	$(MAKE) -f src/sslpp/CMakeFiles/sslpp.dir/build.make src/sslpp/CMakeFiles/sslpp.dir/build
.PHONY : sslpp/fast

#=============================================================================
# Target rules for targets named ssi

# Build rule for target.
ssi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ssi
.PHONY : ssi

# fast build rule for target.
ssi/fast:
	$(MAKE) -f src/ssi/CMakeFiles/ssi.dir/build.make src/ssi/CMakeFiles/ssi.dir/build
.PHONY : ssi/fast

#=============================================================================
# Target rules for targets named thread

# Build rule for target.
thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thread
.PHONY : thread

# fast build rule for target.
thread/fast:
	$(MAKE) -f src/thread/CMakeFiles/thread.dir/build.make src/thread/CMakeFiles/thread.dir/build
.PHONY : thread/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f src/util/CMakeFiles/util.dir/build.make src/util/CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named h2

# Build rule for target.
h2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 h2
.PHONY : h2

# fast build rule for target.
h2/fast:
	$(MAKE) -f src/h2/CMakeFiles/h2.dir/build.make src/h2/CMakeFiles/h2.dir/build
.PHONY : h2/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ls_shmhashstat"
	@echo "... ls_shmstat"
	@echo "... openlitespeed"
	@echo "... adns"
	@echo "... edio"
	@echo "... extensions"
	@echo "... fcgi"
	@echo "... cgi"
	@echo "... jk"
	@echo "... proxy"
	@echo "... registry"
	@echo "... lsapi"
	@echo "... http"
	@echo "... lsquic"
	@echo "... log4cxx"
	@echo "... lsiapi"
	@echo "... lsr"
	@echo "... main"
	@echo "... modgzip"
	@echo "... cache"
	@echo "... modreqparser"
	@echo "... modinspector"
	@echo "... uploadprogress"
	@echo "... mod_security"
	@echo "... modpagespeed"
	@echo "... quic"
	@echo "... lsshm"
	@echo "... socket"
	@echo "... spdy"
	@echo "... sslpp"
	@echo "... ssi"
	@echo "... thread"
	@echo "... util"
	@echo "... h2"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

